### ISSUE TITLE
log_support calculation 

### ISSUE THREAD

**Issue by toogy** [lukauskas/bernoulli-mixture-model#1]
Why not computing the `log_support` with something like this?

```python
for k in range(self.k):                                             
    log_support[k, :] = np.log(pi[k]) \                             
        + np.sum(self.x * np.log(mu[k, :]), 1) \     
        + np.sum((1 - x) * np.log(1 - mu[k, :]), 1)
```

**Comment by lukauskas** [comment]
What is the advantage over the current way?
I'm pretty sure I had something similar and then I modified it to what it is now because it has proven to be faster, but I may be wrong.

**Comment by toogy** [comment]
You are right. I watched your commits history and that's the way you were doing it. :smile:
